version: '3.4'

services:
  # Core Services
  ix.platform.microservice.tenant:
    image: ${DOCKER_REGISTRY:-ix}/ix-platform-microservice-tenant
    build:
      context: .
      dockerfile: src/Services/Core/Tenant/IX.Platform.Microservice.Tenant/Dockerfile

  ix.platform.microservice.admin:
    image: ${DOCKER_REGISTRY:-ix}/ix-platform-microservice-admin
    build:
      context: .
      dockerfile: src/Gateways/IX.Platform.Gateways.Admin/Dockerfile

  # MS SQL Server
  mssqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "mssql-password12345"
       ACCEPT_EULA: "Y"
    ports:
      - 1439:1433
