version: '3.4'

services:
  # Core Services
  ix.platform.microservice.tenant:
    image: ${DOCKER_REGISTRY:-ix}/ix-platform-microservice-tenant
    build:
      context: .
      dockerfile: src/Services/Core/Tenant/IX.Platform.Microservice.Tenant/Dockerfile

  # RabbitMQ
  rabbitmq:
        image: masstransit/rabbitmq:latest
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: always

  # MS SQL Server
  mssqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "mssql-password123"
       ACCEPT_EULA: "Y"
    ports:
      - 1439:1433
