// <auto-generated />
namespace IX.Platform.Core.Tenant.Infrastucture.Migrations

open System
open IX.Platform.Core.Tenant.Infrastucture
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<AppContext.TenantDbContext>)>]
[<Migration("20220813130834_init")>]
type init() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.EnsureSchema(
            name = "IXPPlatform"
            ) |> ignore

        migrationBuilder.CreateTable(
            name = "Tenants"
            ,schema = "IXPPlatform"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Guid>(
                        nullable = false
                        ,``type`` = "uniqueidentifier"
                    )
                CompanyName =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(250)"
                        ,maxLength = Nullable(250)
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Tenants", (fun x -> (x.Id) :> obj)
                    ) |> ignore
                )
        ) |> ignore

        migrationBuilder.InsertData(
            schema = "IXPPlatform",
            table = "Tenants",
            columns = [| "Id"; "CompanyName" |],
            values = [| Guid("18298d08-734a-4566-a0e1-bbaba426d0a0") :> obj; "test company name" :> obj |]
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Tenants"
            ,schema = "IXPPlatform"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasDefaultSchema("IXPPlatform")
            .HasAnnotation("ProductVersion", "6.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128) |> ignore

        modelBuilder.Entity("IX.Platform.Core.Tenant.Contracts.Entities+Tenant", (fun b ->

            b.Property<Guid>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier")
                |> ignore

            b.Property<string>("CompanyName")
                .IsRequired(true)
                .HasMaxLength(250)
                .HasColumnType("nvarchar(250)")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Tenants", "IXPPlatform") |> ignore


            b.HasData([|
                {| Id = Guid("18298d08-734a-4566-a0e1-bbaba426d0a0"); CompanyName = "test company name" |}
             |]) |> ignore
        )) |> ignore

