// <auto-generated />
namespace IX.Platform.Core.Tenant.Infrastucture.Migrations

open System
open IX.Platform.Core.Tenant.Infrastucture
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<AppContext.TenantDbContext>)>]
type TenantDbContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasDefaultSchema("IXPPlatform")
            .HasAnnotation("ProductVersion", "6.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128) |> ignore

        modelBuilder.Entity("IX.Platform.Core.Tenant.Contracts.Entities+Tenant", (fun b ->

            b.Property<Guid>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier")
                |> ignore

            b.Property<string>("CompanyName")
                .IsRequired(true)
                .HasMaxLength(250)
                .HasColumnType("nvarchar(250)")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Tenants", "IXPPlatform") |> ignore


            b.HasData([|
                {| Id = Guid("18298d08-734a-4566-a0e1-bbaba426d0a0"); CompanyName = "test company name" |}
             |]) |> ignore
        )) |> ignore

