apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-microservice
  namespace: default
  labels:
    app: tenant-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-microservice
  template:
    metadata:
      labels:
        app: tenant-microservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tenant-microservice"
        dapr.io/app-port: "80"
        dapr.io/log-level: "info"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
    spec:
      containers:
      - name: tenant-microservice
        image: <registry>/ifx.platform.microservice.tenant:2.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always